version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:13.12-alpine
    command:
      - postgres
      - -c
      - max_connections=250
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: example
      PGDATA: /data/postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5432:5432'
    restart: unless-stopped
