export enum PaymentStatus {
  INITIALIZED = 'INITIALIZED',
  COMPLETED = 'COMPLETED',
  FAILED_PAYMENT = 'FAILED_PAYMENT',
  FAILED_CHECKOUT = 'FAILED_CHECKOUT',
  REFUNDED = 'REFUNDED',
  FAILED_REFUND = 'FAILED_REFUND',
}
