information_gatherer_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is {current_year}.
  expected_output: >
    A list with 10 bullet points of the most relevant information about {topic}
  agent: information_gatherer

# reporting_task:

#   description: > 
#     Review the context provided and gather relevant information for each topic. 
#     Expand each topic into a detailed section for the report, ensuring that it is comprehensive and includes all pertinent information.
#   expected_output: >
#     A full report with main topics, each containing a detailed section of information. 
#     The report should be formatted in markdown and returned as a CSV file with two columns:
#       Column 1: {topic}
#       Column 2: Path to the corresponding markdown file
#   agent: reporting_analyst

# ai_write_task:
#   description: >
#     Summarize the information from the websites into a fully fledge news article in markdown format.
#   expected_output: >
#     A fully fledge news article with the main topics, each with a full section of information.
#     Formatted as markdown without '```'
#   agent: ai_writer

file_write_task:
  description: >
    Write the news article to a file
  expected_output: >
    A fully fledge news article with all information from previous task into a file named markdown/{date}_{topic}.md
    and markdown/{date}_{topic}.md must returned as a CSV file with two columns:
      Column 1: {topic}
      Column 2: Path to the corresponding markdown file
  agent: file_writer