version: '3.8'

services:
  # PostgreSQL service
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
      POSTGRES_DB: ${SQL_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${SQL_PORT}:5432"
    networks:
      - app-network

  #  service (Node.js, NestJS, etc.)
  app:
    build: .
    container_name: qlykho
    environment:
      SQL_HOST: postgres
      SQL_PORT: 5432
      SQL_USER: ${SQL_USER}
      SQL_PASSWORD: ${SQL_PASSWORD}
      SQL_DB: ${SQL_DB}
    ports:
      - "3000:3000"  
    depends_on:
      - postgres
    networks:
      - app-network

# Define a network for app communication
networks:
  app-network:
    driver: bridge

# Volumes to persist PostgreSQL data
volumes:
  postgres-data:
